apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: front
  #annotations:
    #kubernetes.io/change-cause: "unable image"
    #k8s.io/change-cause: "The port 100 has been changed to 110"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
